version: "3"

services:
  jira:
    container_name: jira
    image: jira
    build:
      context: .
      args:
        EXTRAS: "[test]"
    tty: true
    entrypoint: ["bash"]
    volumes:
      - .:/jira